---
- name: subscription
  become: true
  hosts: all
  remote_user: firefly
  
  tasks:

    - name: copy
      synchronize:
        src: gtp-axis-detector
        dest: /opt/glosav/

    - name: copy service
      synchronize:
        src: services/gtp-axis-detector.service
        dest: /lib/systemd/system/

    - name: enable service
      ansible.builtin.command: systemctl enable gtp-axis-detector.service

